[project]
name = "my-deep-research"
version = "0.1.0"
description = "Deep Research CLI demo stack"
requires-python = ">=3.11"
dependencies = [
  "httpx>=0.27",
  "langgraph>=0.1.18",
  "pydantic>=2.5",
  "PyYAML>=6.0",
]

[tool.uv]
dev-dependencies = [
  "pytest>=7.4",
]
