# Copy to config/settings.yaml and adjust for your environment.
# Runtime defaults plus API credentials for the simplified stack
# (OpenRouter for LLM, Tavily for search).

runtime:
  locale: zh-CN
  max_iterations: 6
  human_review: true

models:
  planner: gpt-4o-mini
  researcher: gpt-4o-mini
  reporter: gpt-4o-mini
  temperature: 0.0

search:
  max_queries: 3
  timeout_seconds: 8.0

api:
  openrouter_key: null
  tavily_key: null

observability:
  langsmith_project: deep-research-local
  langsmith_api_key: null
